package gomat

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"encoding/asn1"
	"os"
	"testing"

	"github.com/power2go-com-br/gomat/mattertlv"
)

// setupTestCertManager creates a FileCertManager with a bootstrapped CA in a temp directory.
func setupTestCertManager(t *testing.T) *FileCertManager {
	t.Helper()

	tmpDir := t.TempDir()
	origDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("Getwd: %v", err)
	}
	if err := os.Chdir(tmpDir); err != nil {
		t.Fatalf("Chdir: %v", err)
	}
	t.Cleanup(func() { _ = os.Chdir(origDir) })

	if err := os.MkdirAll("pem", 0o755); err != nil {
		t.Fatalf("MkdirAll pem: %v", err)
	}

	cm := NewFileCertManager(0x110)
	if err := cm.BootstrapCa(); err != nil {
		t.Fatalf("BootstrapCa: %v", err)
	}
	if err := cm.Load(); err != nil {
		t.Fatalf("Load: %v", err)
	}
	return cm
}

// TestNOCCertificateIsNotCA verifies that a Node Operational Certificate
// generated by SignCertificate has IsCA=false in both the parsed x509 cert
// and the raw BasicConstraints DER extension.
func TestNOCCertificateIsNotCA(t *testing.T) {
	cm := setupTestCertManager(t)

	userKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("GenerateKey: %v", err)
	}
	noc, err := cm.SignCertificate(&userKey.PublicKey, 1)
	if err != nil {
		t.Fatalf("SignCertificate: %v", err)
	}

	// Check parsed cert field.
	if noc.IsCA {
		t.Error("NOC x509.Certificate.IsCA should be false, got true")
	}

	// Check raw BasicConstraints extension (OID 2.5.29.19).
	bcOID := asn1.ObjectIdentifier{2, 5, 29, 19}
	var found bool
	for _, ext := range noc.Extensions {
		if ext.Id.Equal(bcOID) {
			found = true
			// DER: SEQUENCE { BOOLEAN <isCA> }
			// 0x30 0x03 0x01 0x01 <value>
			// value: 0xff = true, 0x00 = false
			if len(ext.Value) < 5 {
				t.Fatalf("BasicConstraints extension too short: %x", ext.Value)
			}
			isCAByte := ext.Value[4]
			if isCAByte != 0x00 {
				t.Errorf("BasicConstraints DER has IsCA byte = 0x%02x, want 0x00 (false)", isCAByte)
			}
		}
	}
	if !found {
		t.Error("BasicConstraints extension not found in NOC")
	}
}

// TestCACertificateIsCA verifies that the CA certificate has IsCA=true
// (regression guard — the CA must remain a CA).
func TestCACertificateIsCA(t *testing.T) {
	cm := setupTestCertManager(t)

	caCert := cm.GetCaCertificate()
	if caCert == nil {
		t.Fatal("CA certificate is nil")
	}
	if !caCert.IsCA {
		t.Error("CA certificate IsCA should be true, got false")
	}
}

// TestNOCMatterTLVHasIsCAFalse generates a NOC, serializes it to Matter TLV
// via SerializeCertificateIntoMatter, and verifies the IsCA field is false.
func TestNOCMatterTLVHasIsCAFalse(t *testing.T) {
	cm := setupTestCertManager(t)

	userKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("GenerateKey: %v", err)
	}
	noc, err := cm.SignCertificate(&userKey.PublicKey, 2)
	if err != nil {
		t.Fatalf("SignCertificate: %v", err)
	}

	fabric := &Fabric{
		CertificateManager: cm,
	}
	tlvBytes := SerializeCertificateIntoMatter(fabric, noc)

	// Parse the Matter TLV and navigate to the IsCA field.
	// Structure: anon-struct > list(10) > struct(1) > bool(1)
	parsed, err := mattertlv.Decode(tlvBytes)
	if err != nil {
		t.Fatalf("TLV Decode: %v", err)
	}

	// Use GetItemRec to navigate: tag 10 -> tag 1 -> tag 1
	isCAItem := parsed.GetItemRec([]int{10, 1, 1})
	if isCAItem == nil {
		t.Fatal("Could not find IsCA field in Matter TLV (path 10.1.1)")
	}
	if isCAItem.GetBool() {
		t.Error("Matter TLV IsCA should be false, got true")
	}
}

// TestNOCSerialNumbersAreUnique generates two NOCs from the same CA
// and verifies they have different serial numbers.
func TestNOCSerialNumbersAreUnique(t *testing.T) {
	cm := setupTestCertManager(t)

	key1, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("GenerateKey: %v", err)
	}
	key2, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("GenerateKey: %v", err)
	}

	noc1, err := cm.SignCertificate(&key1.PublicKey, 1)
	if err != nil {
		t.Fatalf("SignCertificate(1): %v", err)
	}
	noc2, err := cm.SignCertificate(&key2.PublicKey, 2)
	if err != nil {
		t.Fatalf("SignCertificate(2): %v", err)
	}

	if noc1.SerialNumber.Cmp(noc2.SerialNumber) == 0 {
		t.Errorf("NOC serial numbers should be unique, but both are %s", noc1.SerialNumber)
	}
}
