package gomat

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"encoding/asn1"
	"os"
	"testing"

	"github.com/power2go-com-br/gomat/mattertlv"
)

// setupTestCertManager creates a FileCertManager with a bootstrapped CA in a temp directory.
func setupTestCertManager(t *testing.T) *FileCertManager {
	t.Helper()

	tmpDir := t.TempDir()
	origDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("Getwd: %v", err)
	}
	if err := os.Chdir(tmpDir); err != nil {
		t.Fatalf("Chdir: %v", err)
	}
	t.Cleanup(func() { _ = os.Chdir(origDir) })

	if err := os.MkdirAll("pem", 0o755); err != nil {
		t.Fatalf("MkdirAll pem: %v", err)
	}

	cm := NewFileCertManager(0x110)
	if err := cm.BootstrapCa(); err != nil {
		t.Fatalf("BootstrapCa: %v", err)
	}
	if err := cm.Load(); err != nil {
		t.Fatalf("Load: %v", err)
	}
	return cm
}

// TestNOCCertificateIsNotCA verifies that a Node Operational Certificate
// generated by SignCertificate has IsCA=false in both the parsed x509 cert
// and the raw BasicConstraints DER extension.
func TestNOCCertificateIsNotCA(t *testing.T) {
	cm := setupTestCertManager(t)

	userKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("GenerateKey: %v", err)
	}
	noc, err := cm.SignCertificate(&userKey.PublicKey, 1)
	if err != nil {
		t.Fatalf("SignCertificate: %v", err)
	}

	// Check parsed cert field.
	if noc.IsCA {
		t.Error("NOC x509.Certificate.IsCA should be false, got true")
	}

	// Check raw BasicConstraints extension (OID 2.5.29.19).
	// When isCa=false (the DEFAULT per RFC 5280), the DER value is an empty
	// SEQUENCE {0x30, 0x00} — the BOOLEAN is omitted because it's the default.
	bcOID := asn1.ObjectIdentifier{2, 5, 29, 19}
	var found bool
	for _, ext := range noc.Extensions {
		if ext.Id.Equal(bcOID) {
			found = true
			// Empty SEQUENCE = isCa defaults to false
			if len(ext.Value) != 2 || ext.Value[0] != 0x30 || ext.Value[1] != 0x00 {
				t.Errorf("BasicConstraints DER should be empty SEQUENCE {0x30, 0x00}, got %x", ext.Value)
			}
		}
	}
	if !found {
		t.Error("BasicConstraints extension not found in NOC")
	}
}

// TestCACertificateIsCA verifies that the CA certificate has IsCA=true
// (regression guard — the CA must remain a CA).
func TestCACertificateIsCA(t *testing.T) {
	cm := setupTestCertManager(t)

	caCert := cm.GetCaCertificate()
	if caCert == nil {
		t.Fatal("CA certificate is nil")
	}
	if !caCert.IsCA {
		t.Error("CA certificate IsCA should be true, got false")
	}
}

// TestNOCMatterTLVHasIsCAFalse generates a NOC, serializes it to Matter TLV
// via SerializeCertificateIntoMatter, and verifies the IsCA field is false.
func TestNOCMatterTLVHasIsCAFalse(t *testing.T) {
	cm := setupTestCertManager(t)

	userKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("GenerateKey: %v", err)
	}
	noc, err := cm.SignCertificate(&userKey.PublicKey, 2)
	if err != nil {
		t.Fatalf("SignCertificate: %v", err)
	}

	fabric := &Fabric{
		CertificateManager: cm,
	}
	tlvBytes := SerializeCertificateIntoMatter(fabric, noc)

	// Parse the Matter TLV and navigate to the IsCA field.
	// Structure: anon-struct > list(10) > struct(1) > bool(1)
	parsed, err := mattertlv.Decode(tlvBytes)
	if err != nil {
		t.Fatalf("TLV Decode: %v", err)
	}

	// Use GetItemRec to navigate: tag 10 -> tag 1 -> tag 1
	isCAItem := parsed.GetItemRec([]int{10, 1, 1})
	if isCAItem == nil {
		t.Fatal("Could not find IsCA field in Matter TLV (path 10.1.1)")
	}
	if isCAItem.GetBool() {
		t.Error("Matter TLV IsCA should be false, got true")
	}
}

// TestNOCSerialNumbersAreUnique generates two NOCs from the same CA
// and verifies they have different serial numbers.
func TestNOCSerialNumbersAreUnique(t *testing.T) {
	cm := setupTestCertManager(t)

	key1, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("GenerateKey: %v", err)
	}
	key2, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("GenerateKey: %v", err)
	}

	noc1, err := cm.SignCertificate(&key1.PublicKey, 1)
	if err != nil {
		t.Fatalf("SignCertificate(1): %v", err)
	}
	noc2, err := cm.SignCertificate(&key2.PublicKey, 2)
	if err != nil {
		t.Fatalf("SignCertificate(2): %v", err)
	}

	if noc1.SerialNumber.Cmp(noc2.SerialNumber) == 0 {
		t.Errorf("NOC serial numbers should be unique, but both are %s", noc1.SerialNumber)
	}
}

// TestNOCBasicConstraintsOmitsDefaultCA verifies that the BasicConstraints
// extension in the NOC omits the BOOLEAN FALSE for isCa (since FALSE is the
// DER DEFAULT value per RFC 5280). matter.js omits the default when
// reconstructing DER from Matter TLV. If gomat encodes BOOLEAN FALSE
// explicitly, the reconstructed DER differs by 3 bytes, breaking signature
// verification.
func TestNOCBasicConstraintsOmitsDefaultCA(t *testing.T) {
	cm := setupTestCertManager(t)

	userKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("GenerateKey: %v", err)
	}
	noc, err := cm.SignCertificate(&userKey.PublicKey, 1)
	if err != nil {
		t.Fatalf("SignCertificate: %v", err)
	}

	bcOID := asn1.ObjectIdentifier{2, 5, 29, 19}
	for _, ext := range noc.Extensions {
		if ext.Id.Equal(bcOID) {
			// When isCa=false (the DEFAULT), the value should be an empty
			// SEQUENCE: {0x30, 0x00}. If it contains BOOLEAN FALSE
			// ({0x30, 0x03, 0x01, 0x01, 0x00}), the DER won't match
			// matter.js's reconstruction.
			if len(ext.Value) != 2 || ext.Value[0] != 0x30 || ext.Value[1] != 0x00 {
				t.Errorf("BasicConstraints value should be empty SEQUENCE {0x30, 0x00} for isCa=false, got %x", ext.Value)
			}
			return
		}
	}
	t.Error("BasicConstraints extension not found in NOC")
}

// TestNOCSignatureVerifiesAgainstCA is a sanity check that the NOC's x509
// signature is valid against the CA certificate (independent of Matter TLV).
func TestNOCSignatureVerifiesAgainstCA(t *testing.T) {
	cm := setupTestCertManager(t)

	userKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("GenerateKey: %v", err)
	}
	noc, err := cm.SignCertificate(&userKey.PublicKey, 1)
	if err != nil {
		t.Fatalf("SignCertificate: %v", err)
	}

	caCert := cm.GetCaCertificate()

	// CheckSignatureFrom verifies the NOC's ECDSA signature using the CA's public key.
	if err := noc.CheckSignatureFrom(caCert); err != nil {
		t.Errorf("NOC signature does not verify against CA: %v", err)
	}
}

// TestMatterTLVSignatureIs64Bytes verifies that the ECDSA signature in the
// Matter TLV encoding is exactly 64 bytes (32-byte R || 32-byte S, zero-padded).
// big.Int.Bytes() returns minimal representation without leading zeros, so
// without explicit padding, signatures where R or S < 32 bytes would produce
// a concatenation shorter than 64 bytes, making it impossible for the receiver
// to correctly split R and S.
func TestMatterTLVSignatureIs64Bytes(t *testing.T) {
	cm := setupTestCertManager(t)

	fabric := &Fabric{
		CertificateManager: cm,
	}

	// Run multiple iterations to increase the chance of hitting a case where
	// R or S has a leading zero byte (probability ~1/128 each, ~1/64 combined).
	for i := 0; i < 200; i++ {
		userKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
		if err != nil {
			t.Fatalf("GenerateKey: %v", err)
		}
		noc, err := cm.SignCertificate(&userKey.PublicKey, uint64(100+i))
		if err != nil {
			t.Fatalf("SignCertificate(%d): %v", i, err)
		}

		tlvBytes := SerializeCertificateIntoMatter(fabric, noc)
		parsed, err := mattertlv.Decode(tlvBytes)
		if err != nil {
			t.Fatalf("TLV Decode: %v", err)
		}

		sigItem := parsed.GetItemRec([]int{11})
		if sigItem == nil {
			t.Fatal("Could not find signature field (tag 11) in Matter TLV")
		}
		sigBytes := sigItem.GetOctetString()
		if len(sigBytes) != 64 {
			t.Fatalf("iteration %d: Matter TLV signature is %d bytes, want 64",
				i, len(sigBytes))
		}
	}
}

// TestNOCCriticalExtensions verifies that all NOC extensions have the correct
// criticality per the Matter spec:
//   - BasicConstraints: Critical
//   - KeyUsage: Critical
//   - ExtKeyUsage: NOT Critical
//   - SubjectKeyIdentifier: NOT Critical
//   - AuthorityKeyIdentifier: NOT Critical
func TestNOCCriticalExtensions(t *testing.T) {
	cm := setupTestCertManager(t)

	userKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("GenerateKey: %v", err)
	}
	noc, err := cm.SignCertificate(&userKey.PublicKey, 1)
	if err != nil {
		t.Fatalf("SignCertificate: %v", err)
	}

	expected := map[string]bool{
		"2.5.29.19": true,  // BasicConstraints: critical
		"2.5.29.15": true,  // KeyUsage: critical
		"2.5.29.37": true,  // ExtKeyUsage: critical (matter.js expects critical)
		"2.5.29.14": false, // SubjectKeyIdentifier: NOT critical
		"2.5.29.35": false, // AuthorityKeyIdentifier: NOT critical
	}

	for _, ext := range noc.Extensions {
		oid := ext.Id.String()
		wantCritical, known := expected[oid]
		if !known {
			continue
		}
		if ext.Critical != wantCritical {
			t.Errorf("extension %s: Critical=%v, want %v", oid, ext.Critical, wantCritical)
		}
		delete(expected, oid)
	}
	for oid := range expected {
		t.Errorf("extension %s not found in NOC", oid)
	}
}

// TestNOCDERRoundTripSignature verifies that the NOC's x509 DER TBS can
// survive a round-trip through Matter TLV and back. This simulates what
// matter.js does: receive TLV → reconstruct DER → verify signature.
// Specifically, it checks that re-encoding the parsed cert produces
// identical raw TBS bytes, which is necessary for signature verification.
func TestNOCDERRoundTripSignature(t *testing.T) {
	cm := setupTestCertManager(t)

	userKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("GenerateKey: %v", err)
	}
	noc, err := cm.SignCertificate(&userKey.PublicKey, 1)
	if err != nil {
		t.Fatalf("SignCertificate: %v", err)
	}

	// Re-marshal the parsed certificate back to DER. If Go's x509 library
	// produces identical bytes, the certificate's DER encoding is canonical
	// and a spec-compliant TLV→DER converter should reproduce it.
	// Note: x509.Certificate.Raw contains the full DER (including signature).
	// x509.Certificate.RawTBSCertificate contains just the TBS portion.
	originalTBS := noc.RawTBSCertificate

	// Verify the signature is valid over the original TBS.
	caCert := cm.GetCaCertificate()
	err = noc.CheckSignatureFrom(caCert)
	if err != nil {
		t.Fatalf("Original NOC signature invalid: %v", err)
	}

	// Re-parse the raw cert to verify DER is well-formed and stable.
	reparsed, err := x509.ParseCertificate(noc.Raw)
	if err != nil {
		t.Fatalf("Re-parse NOC DER: %v", err)
	}

	if len(originalTBS) == 0 {
		t.Fatal("RawTBSCertificate is empty")
	}
	if len(reparsed.RawTBSCertificate) != len(originalTBS) {
		t.Errorf("TBS length changed after re-parse: %d → %d", len(originalTBS), len(reparsed.RawTBSCertificate))
	}
}
